name: iOS Build and Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Test
        run: |
          xcodebuild test \
            -scheme EPCollaboratif \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=18.2' \
            -resultBundlePath TestResults \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()